import About from '@/components/About'
import Main from '@/components/Main'
import Navbar from '@/components/Navbar'
import Skills from '@/components/Skills'

import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Saurabh | Jr.Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Navbar/>
        <Main/>
        <About/>
        <Skills/>

       

     
      </main>
    </>
  )
}
